# Generated by Django 4.0.1 on 2022-01-22 15:32

import Extentions.utils
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='مقدار در url')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Extentions.utils.blog_image_path, verbose_name='تصویر')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('desc', models.TextField(verbose_name='متن مقاله')),
                ('short_desc', models.CharField(max_length=500, verbose_name='متن کوتاه')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شود؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=300, null=True, verbose_name='بیوگرافی')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشک ها',
                'ordering': ['-user__id'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان تخصص')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص \u200cها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DoctorNotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=100, verbose_name='عنوان کوتاه')),
                ('text', models.TextField(max_length=400, verbose_name='متن')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 1, 22, 19, 2, 34, 333986))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.doctormodel', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'نوت پزشک',
                'verbose_name_plural': 'نوت های پرشکان',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='specialties',
            field=models.ManyToManyField(to='MW_Website.SpecialtyModel', verbose_name='تخصص\u200cها'),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نظر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_reply', models.BooleanField(default=False, verbose_name='پاسخ؟')),
                ('is_show', models.BooleanField(default=False, verbose_name='نمایش؟')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.blogmodel', verbose_name='بلاگ')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MW_Website.commentmodel', verbose_name='پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات کاربران',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='categories',
            field=models.ManyToManyField(to='MW_Website.CategoryModel', verbose_name='دسته بندی ها'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(to='MW_Website.TagModel', verbose_name='تگ ها'),
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.doctormodel', verbose_name='نویسنده'),
        ),
        migrations.CreateModel(
            name='BlogLikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.blogmodel', verbose_name='بلاگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست و لایک',
                'verbose_name_plural': 'پست ها و لایک ها',
                'ordering': ['-id'],
            },
        ),
    ]
