# Generated by Django 4.0.1 on 2022-01-10 10:59

import Extentions.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MW_Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialtymodel',
            name='name',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='specialties',
            field=models.ManyToManyField(to='MW_Website.SpecialtyModel', verbose_name='تخصص ها'),
        ),
        migrations.AddField(
            model_name='specialtymodel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان تخصص'),
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('code', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='کد بیمار')),
                ('profile', models.ImageField(blank=True, null=True, upload_to=Extentions.utils.patient_image_path, verbose_name='پروفایل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
                'ordering': ['-user__id'],
            },
        ),
    ]
