# Generated by Django 4.0.1 on 2022-01-11 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='منتشر شود؟'),
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 21, 12, 16, 711237)),
        ),
    ]
