# Generated by Django 4.0.1 on 2022-01-10 11:16

import Extentions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0002_remove_specialtymodel_name_doctormodel_specialties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='code',
            field=models.AutoField(default='67742778', editable=False, primary_key=True, serialize=False, unique=True, verbose_name='کد دکتر'),
        ),
        migrations.AlterField(
            model_name='patientmodel',
            name='code',
            field=models.AutoField(default=Extentions.utils.get_patient_code, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='کد بیمار'),
        ),
    ]
