# Generated by Django 4.0.1 on 2022-01-16 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0002_commentmodel_is_show_alter_doctormodel_specialties_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 0, 22, 51, 533670)),
        ),
        migrations.DeleteModel(
            name='CommentLikesModel',
        ),
    ]
