# Generated by Django 4.0.1 on 2022-01-13 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0002_blogmodel_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 10, 28, 3, 963061)),
        ),
    ]
