# Generated by Django 4.0.1 on 2022-01-27 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0003_alter_doctornotesmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 13, 37, 11, 638006)),
        ),
    ]
