# Generated by Django 4.0.1 on 2022-01-10 12:08

import Extentions.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0003_alter_doctormodel_code_alter_patientmodel_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctormodel',
            options={'ordering': ['-user__id'], 'verbose_name': 'پزشک', 'verbose_name_plural': 'پزشک ها'},
        ),
        migrations.AlterField(
            model_name='doctormodel',
            name='code',
            field=models.AutoField(default=Extentions.utils.get_doctor_code, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='کد پزشک'),
        ),
        migrations.CreateModel(
            name='DoctorNotesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(max_length=100, verbose_name='عنوان کوتاه')),
                ('text', models.TextField(max_length=400, verbose_name='متن')),
                ('created', models.DateTimeField(default=datetime.datetime(2022, 1, 10, 15, 38, 1, 266717))),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.doctormodel', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'نوت پزشک',
                'verbose_name_plural': 'نوت های پرشکان',
                'ordering': ['-id'],
            },
        ),
    ]
