# Generated by Django 4.0.1 on 2022-01-10 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0004_alter_doctormodel_options_alter_doctormodel_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 15, 52, 33, 977820)),
        ),
    ]
