# Generated by Django 4.0.1 on 2022-01-10 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0005_alter_doctornotesmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 16, 11, 59, 207549)),
        ),
    ]
