# Generated by Django 4.0.1 on 2022-01-10 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0006_alter_doctornotesmodel_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 16, 39, 22, 814818)),
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('desc', models.TextField(verbose_name='متن مقاله')),
                ('short_desc', models.CharField(max_length=500, verbose_name='متن کوتاه')),
                ('is_liked', models.BooleanField(default=False, verbose_name='لایک؟')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='MW_Website.CategoryModel', verbose_name='دسته بندی ها')),
                ('tags', models.ManyToManyField(to='MW_Website.TagModel', verbose_name='تگ ها')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.doctormodel', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
                'ordering': ['-id'],
            },
        ),
    ]
