# Generated by Django 4.0.1 on 2022-01-28 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0006_alter_doctornotesmodel_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 20, 1, 54, 767084)),
        ),
    ]
