# Generated by Django 4.0.1 on 2022-01-10 13:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MW_Website', '0007_categorymodel_tagmodel_doctormodel_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 17, 2, 27, 270660)),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نظر')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_reply', models.BooleanField(default=False, verbose_name='پاسخ؟')),
                ('is_like', models.BooleanField(default=False, verbose_name='لایک؟')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.blogmodel', verbose_name='بلاگ')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MW_Website.commentmodel', verbose_name='پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات کاربران',
                'ordering': ['-id'],
            },
        ),
    ]
