# Generated by Django 4.0.1 on 2022-01-28 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0008_alter_datamodel_data_alter_doctornotesmodel_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 20, 16, 44, 911428)),
        ),
    ]
