# Generated by Django 4.0.1 on 2022-01-10 20:03

import Extentions.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0008_alter_doctornotesmodel_created_commentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Extentions.utils.blog_image_path, verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 23, 33, 17, 399733)),
        ),
    ]
