# Generated by Django 4.0.1 on 2022-01-10 20:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MW_Website', '0009_blogmodel_image_alter_doctornotesmodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='is_liked',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد لایک\u200cها'),
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 10, 23, 59, 48, 600083)),
        ),
        migrations.CreateModel(
            name='CommentLikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.commentmodel', verbose_name='نظر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر و لایک',
                'verbose_name_plural': 'نظرات و لایک ها',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BlogLikesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MW_Website.blogmodel', verbose_name='بلاگ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست و لایک',
                'verbose_name_plural': 'پست ها و لایک ها',
                'ordering': ['-id'],
            },
        ),
    ]
