# Generated by Django 4.0.1 on 2022-01-28 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0009_datamodel_task_id_alter_doctornotesmodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 20, 28, 51, 522511)),
        ),
    ]
