# Generated by Django 4.0.1 on 2022-01-10 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0010_remove_blogmodel_is_liked_blogmodel_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='commentmodel',
            name='is_like',
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 11, 0, 1, 58, 378263)),
        ),
    ]
