# Generated by Django 4.0.1 on 2022-01-28 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Website', '0010_remove_datamodel_task_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datamodel',
        ),
        migrations.AlterField(
            model_name='doctornotesmodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 20, 32, 52, 237179)),
        ),
    ]
