# Generated by Django 4.0.1 on 2022-01-10 12:22

import Extentions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to=Extentions.utils.brands_image_path, verbose_name='تصویر برند')),
            ],
            options={
                'verbose_name': 'تصویر برند\u200c',
                'verbose_name_plural': 'تصاویر برند\u200cها',
                'ordering': ['-id'],
            },
        ),
    ]
