# Generated by Django 4.0.1 on 2022-01-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
            ],
            options={
                'verbose_name': 'ایمیل - ارسال خبر',
                'verbose_name_plural': 'ایمیل\u200cها - ارسال اخبار',
                'ordering': ['-id'],
            },
        ),
    ]
