# Generated by Django 4.0.1 on 2022-01-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MW_Setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='متن ارتباط')),
                ('name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل کاربر')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان ارتباط')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پیام مخاطب',
                'verbose_name_plural': 'پیام های مخاطبان',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_scale', models.FloatField(blank=True, null=True, verbose_name='مقیاس ایکس')),
                ('y_scale', models.FloatField(blank=True, null=True, verbose_name='مقیاس ایگرگ')),
                ('marker_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='متن شما روی نقشه')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='کشور')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='استان')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='شهرستان')),
                ('phone', models.PositiveBigIntegerField(verbose_name='تلفن')),
                ('from_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='زمان گشایش')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('your_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن شما درمورد ارتباط')),
            ],
            options={
                'verbose_name': '\u200cتنظیمات',
                'verbose_name_plural': '\u200cتنظیمات',
                'ordering': ['-id'],
            },
        ),
    ]
